# -*- coding: utf-8 -*-
"""HW8_1ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sIeXi9RAi6Ne9MIJHFUfCkg4Hukf0pdN
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import cv2
from google.colab.patches import cv2_imshow
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, ConfusionMatrixDisplay
from sklearn.naive_bayes import GaussianNB
import seaborn as sns

dfTrain=pd.read_csv('/content/fashion-mnist_train.csv')
X=np.array(dfTrain.iloc[:,1:])
y=np.array(dfTrain.iloc[:,0])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
model = GaussianNB().fit(X_train, y_train)
number = cv2.cvtColor(cv2.imread('/content/tShirt_original.bmp'), cv2.COLOR_BGR2GRAY)
cv2_imshow(number)
number = cv2.resize(number, (28, 28))
number = number.reshape(1, 28 * 28)
print(f'Predicted:{model.predict(number)}')