# -*- coding: utf-8 -*-
"""HW8_2ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHkBF8XDbe5h_Lb2UdToKfGJ-lZ8l5mb
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import cv2
from google.colab.patches import cv2_imshow
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, ConfusionMatrixDisplay
from sklearn.linear_model import LogisticRegression
import seaborn as sns

dfTrain=pd.read_csv('/content/fashion-mnist_train.csv')
X=np.array(dfTrain.iloc[:,1:])
y=np.array(dfTrain.iloc[:,0])
model=LogisticRegression().fit(X, y)
number = cv2.cvtColor(cv2.imread('/content/tShirt_original.bmp'), cv2.COLOR_BGR2GRAY)
cv2_imshow(number)
number = cv2.resize(number, (28, 28))
number = number.reshape(1, 28 * 28)
print(f'Predicted:{model.predict(number)}')
#print(f'number:{number}')
#print(f'Coef: {model.coef_}')
#print(f'Coef shape: {model.coef_.shape}')
#print(f'Intercept: {model.intercept_}')